apiVersion: apps/v1
kind: Deployment
metadata:
  name: tagalys-sql-server
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: sql-server
  template:
    metadata:
      labels:
        pod: sql-server
    spec:
      volumes: # use this instad of env
        - name: mysql-config-volume
          configMap:
            name: mysql-config
        - name: secret-sql-volume
          secret:
            secretName: tagalys-secret
        - name: sql-storage
          persistentVolumeClaim:
            claimName: tagalys-sql-storage-claim
      containers:
        - name: sql-server-container
          image: mysql
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: sql-storage
              mountPath: "/var/lib/data"
            - name: secret-sql-volume
              mountPath: "/mnt/secret"
              readOnly: true
            - name: mysql-config-volume ## specify volume name
              mountPath: /etc/mysql/conf.d/default_auth.cnf ## path to mount file
              subPath: default_auth
          env:
            - name: "MYSQL_ALLOW_EMPTY_PASSWORD"
              value: "1"
            # - name: "MYSQL_ROOT_PASSWORD"
            #   valueFrom:
            #     secretKeyRef:
            #       name: tagalys-secret
            #       key: MYSQL_ROOT_PASSWORD
            # - name: "MYSQL_DATABASE"
            #   valueFrom:
            #     secretKeyRef:
            #       name: tagalys-secret
            #       key: MYSQL_DATABASE
            # - name: "MYSQL_USER"
            #   valueFrom:
            #     secretKeyRef:
            #       name: tagalys-secret
            #       key: MYSQL_USER
            # - name: "MYSQL_PASSWORD"
            #   valueFrom:
            #     secretKeyRef:
            #       name: tagalys-secret
            #       key: MYSQL_PASSWORD
            # - name: "MYSQL_ROOT_HOST"
            #   valueFrom:
            #     secretKeyRef:
            #       name: tagalys-secret
            #       key: MYSQL_ROOT_HOST
          args: ["--default-authentication-plugin=mysql_native_password","--ignore-db-dir=lost+found"]


---

# config-map.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  ## name of ConfigMap. This will be referred from volume definition
  name: mysql-config
  labels:
    app: mysql
data:
  ## default_auth is the name of config. This will be referred from volume mount definition
  default_auth: |
    [mysqld]
    default_authentication_plugin= mysql_native_password


# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: initdb
# data:
#   initdb.sql: |-
#     UPDATE mysql.user SET host = '%' WHERE host = 'localhost';
#     ALTER USER root@% IDENTIFIED WITH mysql_native_password BY 'password';