apiVersion: v1
kind: Secret
metadata:
  name: tagalys-secret
type: Opaque
stringData:
  TAGALYS_SECRET: "I'm in secrtes.yml but I'm referenced from /mnt/secret/TAGALYS_SECRET"
  DB_USER: "root"
  DB_NAME: "fakedb"
  DB_PASSWORD: ""
  DB_HOST: "tagalys-sql-server-cluster-ip"
  DEV_SECRET_KEY: "3eb91b8eec6021b5169317eca6f4f7ae3b5143cad47097a2bc64796964d35aa7ba6ef2dcd0b187ac3a171be3cf8ee76b0b846942d2f47dc704eae400df9b857b"
  PROD_SECRET_KEY: "sample_prod_key"
  TEST_SECRET_KEY: "bb7fdc2a331f54867cf9a1c3ce0240e01fff09ccf2e123b5796610f1273a46617cc80c3ec000fb882dfeba9b63f84648fd069a0daf694fcf7336dfcdd46236cd"
  MYSQL_ROOT_PASSWORD: ""
  MYSQL_DATABASE: "fakedb"
  MYSQL_USER: "root"
  MYSQL_PASSWORD: ""
  MYSQL_ROOT_HOST: "%"
